/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HudRouteImport } from './routes/hud'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TrayRouteImport } from './routes/tray'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HudRoute = HudRouteImport.update({
  id: '/hud',
  path: '/hud',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TrayRoute = TrayRouteImport.update({
  id: '/tray',
  path: '/tray',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hud': typeof HudRoute
  '/settings': typeof SettingsRoute
  '/tray': typeof TrayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hud': typeof HudRoute
  '/settings': typeof SettingsRoute
  '/tray': typeof TrayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hud': typeof HudRoute
  '/settings': typeof SettingsRoute
  '/tray': typeof TrayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hud' | '/settings' | '/tray'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hud' | '/settings' | '/tray'
  id: '__root__' | '/' | '/hud' | '/settings' | '/tray'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HudRoute: typeof HudRoute
  SettingsRoute: typeof SettingsRoute
  TrayRoute: typeof TrayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hud': {
      id: '/hud'
      path: '/hud'
      fullPath: '/hud'
      preLoaderRoute: typeof HudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tray': {
      id: '/tray'
      path: '/tray'
      fullPath: '/tray'
      preLoaderRoute: typeof TrayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HudRoute: HudRoute,
  SettingsRoute: SettingsRoute,
  TrayRoute: TrayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
